# Generated by InFoundry
# Pattern: serverless

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# API_GATEWAY
resource "aws_api_gateway_rest_api" "main" {
  name = "infoundry-api"
}

# LAMBDA_FUNCTIONS
resource "aws_lambda_function" "main" {
  function_name = "infoundry-handler"
  runtime = "python3.11"
  handler = "main.handler"
  role = aws_iam_role.lambda.arn
}

# DYNAMODB
resource "aws_dynamodb_table" "main" {
  name = "infoundry-data"
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "id"

  attribute {
    name = "id"
    type = "S"
  }
}
